security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: 
                login_path: /project/login
                check_path: /project/login_check
            logout:
                path: /project/logout
                target: /
    access_control:
        - { path: ^/project/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/project, roles: ROLE_USER}

    providers:
#        main:
#          entity: { class: ScenarioEdUserBundle:User, property: username }
#        administrators:
#            entity: { class: ScenarioEdUserBundle:User, property: username }
        in_memory:
            memory:
                users:
                    melissa:  { password: dorpgorp, roles: 'ROLE_USER' }
                    admin: { password: admindorp, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#         ScenarioEd\UserBundle\Entity\User:
#            algorithm:        sha1
#            encode_as_base64: false
#            iterations:       1
